# Generated by Django 4.1 on 2022-09-06 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('balance', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=60)),
                ('open_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('transid', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('dot', models.DateField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bankapp.cust')),
            ],
        ),
    ]
